name: check

on: 
  push:
    #schedule:
    #   - cron: '0 12 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: perl alarm
      run: perl timer.pl
    - name: irssi
      working-directory: irssi
      run: ./test-irssi.sh
